# Generated by Django 5.1.6 on 2025-03-01 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport_optimization_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('travel_time_seconds', models.IntegerField(help_text='Time to travel between start and end stop in seconds')),
                ('distance_meters', models.IntegerField(help_text='Distance between start and end stop in meters')),
                ('end_stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='end_stop', to='transport_optimization_app.stop')),
                ('start_stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='start_stop', to='transport_optimization_app.stop')),
            ],
            options={
                'unique_together': {('start_stop', 'end_stop')},
            },
        ),
    ]
