# Generated by Django 5.1.6 on 2025-03-01 15:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport_optimization_app', '0002_traveltime'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='traveltime',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='traveltime',
            name='time_of_day',
            field=models.TimeField(default=datetime.time(0, 0), help_text='Time of day for this travel time'),
        ),
        migrations.AlterUniqueTogether(
            name='traveltime',
            unique_together={('start_stop', 'end_stop', 'time_of_day')},
        ),
    ]
