# Generated by Django 5.1.7 on 2025-04-05 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport_optimization_app', '0003_alter_traveltime_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stop',
            name='is_final_stop',
            field=models.BooleanField(default=False),
        ),
    ]
