# Generated by Django 5.1.7 on 2025-04-05 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport_optimization_app', '0005_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='stop',
            name='city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='transport_optimization_app.city'),
            preserve_default=False,
        ),
    ]
