# Generated by Django 5.1.7 on 2025-04-05 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport_optimization_app', '0006_stop_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stop',
            name='is_final_stop',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='traveltime',
            name='time_of_day',
            field=models.TimeField(help_text='Time of day for this travel time'),
        ),
    ]
