# Generated by Django 5.1.7 on 2025-04-05 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transport_optimization_app', '0007_alter_stop_is_final_stop_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='frequency',
        ),
    ]
